"""Renders an AuditReport as Markdown and/or JSON."""

from __future__ import annotations

import json
from pathlib import Path

from .audit import AuditReport, ConnectorAuditEntry
from .versioning import Staleness

_STALENESS_LABEL = {
    Staleness.UP_TO_DATE: "Up to date",
    Staleness.MINOR_BEHIND: "Minor/patch behind",
    Staleness.MAJOR_BEHIND: "MAJOR version behind",
    Staleness.NOT_FOUND: "Not found on Maven Central",
    Staleness.UNPINNED: "No pinned version",
}

_STALENESS_ICON = {
    Staleness.UP_TO_DATE: "OK",
    Staleness.MINOR_BEHIND: "WARN",
    Staleness.MAJOR_BEHIND: "STALE",
    Staleness.NOT_FOUND: "N/A",
    Staleness.UNPINNED: "N/A",
}


def _filter_entries(entries: list[ConnectorAuditEntry], major_behind_only: bool) -> list[ConnectorAuditEntry]:
    if not major_behind_only:
        return entries
    return [e for e in entries if e.staleness == Staleness.MAJOR_BEHIND]


def render_markdown(report: AuditReport, major_behind_only: bool = False) -> str:
    lines: list[str] = []
    lines.append(f"# Mule Connector Audit -- {report.pom_path}")
    lines.append("")
    lines.append(
        "Generated by `mule-connector-audit` from a deterministic parse of the "
        "pom.xml plus a live query against the real Maven Central Search API "
        "(`search.maven.org`). No LLM was involved in producing this report."
    )
    lines.append("")

    counts = report.counts()
    lines.append(
        f"Scanned {report.total_dependencies} total dependenc"
        f"{'y' if report.total_dependencies == 1 else 'ies'}, "
        f"{len(report.entries)} identified as MuleSoft connector(s)."
    )
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Up to date: **{counts[Staleness.UP_TO_DATE.value]}**")
    lines.append(f"- Minor/patch behind: **{counts[Staleness.MINOR_BEHIND.value]}**")
    lines.append(f"- MAJOR version behind: **{counts[Staleness.MAJOR_BEHIND.value]}**")
    lines.append(f"- Not found on Maven Central: **{counts[Staleness.NOT_FOUND.value]}**")
    lines.append(f"- No pinned version: **{counts[Staleness.UNPINNED.value]}**")
    lines.append(f"- Possibly abandoned (no release in 2+ years): **{counts['possibly-abandoned']}**")
    lines.append("")

    entries = _filter_entries(report.entries, major_behind_only)
    if major_behind_only:
        lines.append(
            f"_Filtered view: showing only {len(entries)} connector(s) that are "
            f"a MAJOR version behind (`--major-behind-only`)._"
        )
        lines.append("")

    if not entries:
        lines.append("No connectors to report." if not report.entries else "No connectors match the filter.")
        lines.append("")
    else:
        lines.append("## Connectors")
        lines.append("")
        lines.append("| Connector | Pinned | Latest (Maven Central) | Status | Last release | Abandoned? |")
        lines.append("|---|---|---|---|---|---|")
        for e in entries:
            pinned = e.pinned_version or "_(unresolved)_"
            latest = e.latest_version or "_(none)_"
            status = f"{_STALENESS_ICON[e.staleness]}: {_STALENESS_LABEL[e.staleness]}"
            abandoned = "yes" if e.possibly_abandoned else ("-" if e.lookup and e.lookup.found else "n/a")
            lines.append(
                f"| `{e.group_id}:{e.artifact_id}` | `{pinned}` | `{latest}` | {status} "
                f"| {e.release_date_str} | {abandoned} |"
            )
        lines.append("")

        lines.append("## Details")
        lines.append("")
        for e in entries:
            lines.append(f"### `{e.group_id}:{e.artifact_id}`")
            lines.append("")
            lines.append(e.detail)
            lines.append("")

    return "\n".join(lines)


def render_json(report: AuditReport, major_behind_only: bool = False) -> str:
    entries = _filter_entries(report.entries, major_behind_only)
    payload = {
        "pom_path": str(report.pom_path),
        "total_dependencies": report.total_dependencies,
        "connector_count": len(report.entries),
        "summary": report.counts(),
        "connectors": [
            {
                "group_id": e.group_id,
                "artifact_id": e.artifact_id,
                "pinned_version": e.pinned_version,
                "latest_version": e.latest_version,
                "found_on_maven_central": bool(e.lookup and e.lookup.found),
                "staleness": e.staleness.value,
                "possibly_abandoned": e.possibly_abandoned,
                "days_since_release": e.days_since_release,
                "last_release_date": e.release_date_str,
                "detail": e.detail,
            }
            for e in entries
        ],
    }
    return json.dumps(payload, indent=2)


def write_report(
    report: AuditReport,
    out_path: str | Path,
    json_out_path: str | Path | None = None,
    major_behind_only: bool = False,
) -> None:
    out_path = Path(out_path)
    out_path.write_text(render_markdown(report, major_behind_only=major_behind_only), encoding="utf-8")
    if json_out_path is not None:
        Path(json_out_path).write_text(
            render_json(report, major_behind_only=major_behind_only), encoding="utf-8"
        )
